file(MAKE_DIRECTORY "${WORK}")
# Original literal instructions, never a proprietary firmware fixture.
execute_process(COMMAND "${PYTHON}" -c
  "from pathlib import Path; import sys; p=Path(sys.argv[1]); (p/'original rom.bin').write_bytes(b''.join(w.to_bytes(4,'little') for w in [0x3c01a000,0x2402002a,0xac220100,0x1000ffff,0])); (p/'fault.bin').write_bytes((0x0000080f).to_bytes(4,'little')); (p/'empty.bin').write_bytes(b''); (p/'short.bin').write_bytes(b'x'); f=(p/'large.bin').open('wb'); f.truncate(4194305); f.close()"
  "${WORK}" RESULT_VARIABLE fixture_code)
if(NOT fixture_code EQUAL 0)
  message(FATAL_ERROR "Could not create original boot ROM fixtures")
endif()
function(run expected_code expected_text)
  execute_process(COMMAND "${CLI}" --bios ${ARGN} RESULT_VARIABLE code
    OUTPUT_VARIABLE output ERROR_VARIABLE error TIMEOUT 20)
  if(NOT "${code}" STREQUAL "${expected_code}")
    message(FATAL_ERROR "${ARGN}: exit ${code}, expected ${expected_code}: ${output} / ${error}")
  endif()
  if(expected_code EQUAL 0)
    if(NOT error STREQUAL "" OR NOT output MATCHES "${expected_text}")
      message(FATAL_ERROR "${ARGN}: unexpected output: ${output} / ${error}")
    endif()
  elseif(NOT error MATCHES "${expected_text}")
    message(FATAL_ERROR "${ARGN}: missing error: ${error}")
  endif()
endfunction()
run(0 "Boot ROM loaded: entry=0xbfc00000 file-bytes=20" "${WORK}/original rom.bin" --steps 0)
run(0 "retired=0 pc=0xbfc00000 budget-exhausted" "${WORK}/original rom.bin" --steps 0)
run(0 "inspect.0x00000100.=0x0000002a" "${WORK}/original rom.bin" --steps 3 --inspect 0x100)
run(0 "inspect.0xbfc00000.=0x3c01a000" "${WORK}/original rom.bin" --steps 0 --inspect 0xbfc00000)
run(0 "pc=0xbfc00010 opcode=0x00000000 delay-slot retired" "${WORK}/original rom.bin" --steps 5 --trace)
run(0 "retired=1000 pc=0xbfc00010 budget-exhausted" "${WORK}/original rom.bin")
run(1 "pc=0xbfc00000 opcode=0x0000080f: unsupported" "${WORK}/fault.bin" --trace)
run(1 "cannot open Boot ROM file" "${WORK}/missing.bin")
run(1 "boot ROM must contain 1 through 4194304 bytes" "${WORK}/empty.bin")
run(1 "boot ROM bytes are not loaded for this range" "${WORK}/short.bin")
run(1 "Boot ROM file exceeds its size limit" "${WORK}/large.bin")
run(1 "boot ROM bytes are not loaded for this range" "${WORK}/original rom.bin" --inspect 0xbfc00020)
run(2 "Usage:")
run(2 "Usage:" "${WORK}/original rom.bin" --trace --trace)
run(2 "Usage:" "${WORK}/original rom.bin" --steps)
run(2 "Invalid step budget" "${WORK}/original rom.bin" --steps 100001)
run(2 "Invalid step budget" "${WORK}/original rom.bin" --steps -1)
run(2 "Invalid inspect address" "${WORK}/original rom.bin" --inspect 0xbfc00001)
execute_process(COMMAND "${CLI}" --bios "${WORK}/original rom.bin" --steps 11 --trace --inspect 0x100
  RESULT_VARIABLE first_code OUTPUT_VARIABLE first ERROR_VARIABLE first_error TIMEOUT 20)
execute_process(COMMAND "${CLI}" --bios "${WORK}/original rom.bin" --steps 11 --trace --inspect 0x100
  RESULT_VARIABLE second_code OUTPUT_VARIABLE second ERROR_VARIABLE second_error TIMEOUT 20)
if(NOT first_code EQUAL 0 OR NOT second_code EQUAL 0 OR NOT first STREQUAL second
   OR NOT first_error STREQUAL "" OR NOT second_error STREQUAL "")
  message(FATAL_ERROR "Boot ROM CLI output was not deterministic")
endif()
