function(check_cli expected_code expected_output)
  execute_process(COMMAND "${CLI}" ${ARGN}
    RESULT_VARIABLE code OUTPUT_VARIABLE output ERROR_VARIABLE error TIMEOUT 5)
  if(NOT "${code}" STREQUAL "${expected_code}")
    message(FATAL_ERROR "${ARGN}: exit ${code}, expected ${expected_code}: ${error}")
  endif()
  if(expected_code EQUAL 0)
    if(NOT output MATCHES "${expected_output}" OR NOT error STREQUAL "")
      message(FATAL_ERROR "${ARGN}: unexpected stdout/stderr: ${output} / ${error}")
    endif()
  else()
    if(NOT error MATCHES "${expected_output}" OR NOT output STREQUAL "")
      message(FATAL_ERROR "${ARGN}: unexpected stdout/stderr: ${output} / ${error}")
    endif()
  endif()
endfunction()

check_cli(0 "tick=0 ")
check_cli(0 "Usage: critterlink" --help)
check_cli(0 "tick=42 " --ticks 42)
check_cli(0 "tick=18446744073709551615 " --ticks 18446744073709551615)
check_cli(2 "Usage:" --unknown)
check_cli(2 "Usage:" --ticks)
check_cli(2 "Usage:" --ticks 1 extra)
check_cli(2 "Usage:" --help extra)
foreach(invalid IN ITEMS -1 +1 1.5 1x " 1" 18446744073709551616)
  check_cli(2 "Invalid tick count" --ticks "${invalid}")
endforeach()
# Preserve an explicitly empty argument rather than expanding a CMake list.
execute_process(COMMAND "${CLI}" --ticks "" RESULT_VARIABLE code
  OUTPUT_VARIABLE output ERROR_VARIABLE error TIMEOUT 5)
if(NOT code EQUAL 2 OR NOT error MATCHES "Invalid tick count" OR NOT output STREQUAL "")
  message(FATAL_ERROR "Empty tick argument was not rejected correctly")
endif()
