function(check_cli expected_code expected_output)
  execute_process(COMMAND "${CLI}" ${ARGN}
    RESULT_VARIABLE code OUTPUT_VARIABLE output ERROR_VARIABLE error TIMEOUT 20)
  if(NOT "${code}" STREQUAL "${expected_code}")
    message(FATAL_ERROR "${ARGN}: exit ${code}, expected ${expected_code}: ${error}")
  endif()
  if(expected_code EQUAL 0)
    if(NOT output MATCHES "${expected_output}" OR NOT error STREQUAL "")
      message(FATAL_ERROR "${ARGN}: unexpected stdout/stderr: ${output} / ${error}")
    endif()
  else()
    if(NOT error MATCHES "${expected_output}" OR NOT output STREQUAL "")
      message(FATAL_ERROR "${ARGN}: unexpected stdout/stderr: ${output} / ${error}")
    endif()
  endif()
endfunction()

check_cli(0 "tick=0 ")
check_cli(0 "Usage: critterlink" --help)
check_cli(0 "tick=42 " --ticks 42)
check_cli(0 "tick=18446744073709551615 " --ticks 18446744073709551615)
check_cli(2 "Usage:" --unknown)
check_cli(2 "Usage:" --ticks)
check_cli(2 "Usage:" --ticks 1 extra)
check_cli(2 "Usage:" --help extra)
check_cli(0 "ticks=64 sprite-pixels=12 int0=1 int1=1 replay=identical" --hardware-demo)
check_cli(2 "Usage:" --hardware-demo extra)
check_cli(0 "ticks=128 timer-services=1 dma-services=1 sprite-pixels=12 acknowledged=1 returned=1 replay=identical" --interrupt-demo)
check_cli(2 "Usage:" --interrupt-demo extra)
check_cli(0 "output=7,9,11,13 dma-completed=1 replay=identical" --vector-demo)
check_cli(2 "Usage:" --vector-demo extra)
check_cli(0 "response=40 exchange-completed=1 replay=identical" --iop-demo)
check_cli(2 "Usage:" --iop-demo extra)
check_cli(0 "ticks=135 samples=135 signature=13041860280187223349 audible=1 released=1 replay=identical" --spu-demo)
check_cli(2 "Usage:" --spu-demo extra)
check_cli(0 "ticks=1185 digital=1 analog=1 card=1 disc=1 replay=identical" --io-demo)
check_cli(2 "Usage:" --io-demo extra)
check_cli(0 "ticks=194 sprite-pixels=12 samples=194 pcm-signature=15153771150353129381 concurrent=1 input=1 replay=identical" --integrated-demo)
check_cli(2 "Usage:" --integrated-demo extra)
check_cli(0 "retired=25 pc=36 r2=15 r3=5 r4=15 r5=143 ram.256.=15 budget-exhausted" --demo)
check_cli(0 "retired=0 pc=0" --demo --steps 0)
check_cli(0 "pc=0x00000014 opcode=0x24630001 delay-slot retired" --demo --trace)
check_cli(0 "retired=1 pc=4" --demo --trace --steps 1)
check_cli(2 "Invalid step budget" --demo --steps 100001)
check_cli(2 "Invalid step budget" --demo --steps -1)
check_cli(2 "Usage:" --demo --steps)
check_cli(2 "Usage:" --demo --trace --trace)
check_cli(2 "Usage:" --demo --steps 1 --steps 2)
check_cli(2 "Usage:" --demo --ticks 2)
foreach(invalid IN ITEMS -1 +1 1.5 1x " 1" 18446744073709551616)
  check_cli(2 "Invalid tick count" --ticks "${invalid}")
endforeach()
# Preserve an explicitly empty argument rather than expanding a CMake list.
execute_process(COMMAND "${CLI}" --ticks "" RESULT_VARIABLE code
  OUTPUT_VARIABLE output ERROR_VARIABLE error TIMEOUT 5)
if(NOT code EQUAL 2 OR NOT error MATCHES "Invalid tick count" OR NOT output STREQUAL "")
  message(FATAL_ERROR "Empty tick argument was not rejected correctly")
endif()

# Running beyond the fixture reaches its result word, which is a valid SYNC.
# The explicit invalid-opcode ELF case tests the CPU-fault CLI path separately.
execute_process(COMMAND "${CLI}" --demo --steps 100 --trace RESULT_VARIABLE code
  OUTPUT_VARIABLE output ERROR_VARIABLE error TIMEOUT 5)
if(NOT code EQUAL 0 OR NOT error STREQUAL ""
   OR NOT output MATCHES "pc=0x00000100 opcode=0x0000000f retired"
   OR NOT output MATCHES "retired=100 pc=336" OR NOT output MATCHES "budget-exhausted")
  message(FATAL_ERROR "Extended demo SYNC contract failed: ${code}: ${output} / ${error}")
endif()
